apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity
  region: us-east-1

managedNodeGroups:
  - name: ng-REPLACE-workers
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 80
    privateNetworking: false

availabilityZones: ["us-east-1a", "us-east-1b"]
